#!/bin/bash
(find . -name "*.less") | while read -r line ; do
  echo "Processing $line"
  filename=$(basename -- "$line")
  ext_filename=${filename%.less}.css
  lessc $line public_html/$ext_filename
done
